#!/usr/bin/env python
"""
Usage: hashpass [options] [<website>]

Options:
    -g --gui     Start the GUI. (ignores all other options)
    -s --show    Display the site password instead of putting it in the clipboard
    -b --bcrypt  Use bcrypt as the hashing algorithm [Default]
    --sha        Use sha256 as the hashing algorithm [Old, flawed]
"""
import sys
import os
from docopt import docopt
import pinentry
import getpass
import hashpasslib

def init():
    """ Saves the master password to disk if you haven't already """
    if not hashpasslib.read_stored_master():
        secret_master = getpass.getpass("No master password found. Enter one now: ")
        hashpasslib.store_master(secret_master)
        print "Your master password will be hashed and saved at " + MASTER_PW_PATH

def get_password_cli(use_bcrypt):
    """ Gets the password via CLI and makes sure it matches the stored password """
    pw = getpass.getpass("Enter master password: ")
    while not hashpasslib.is_correct_master(pw):
        print "That doesn't match the stored master."
        pw = getpass.getpass("Try again: ")
    hashpasslib.use_master(pw, use_bcrypt)

def get_password(use_bcrypt):
    """ Gets the password via pinentry if possible. Fallback to CLI. """
    try:
        pw = pinentry.get_pin(description="Enter hashpass master password:",
                              prompt="Password:")
        while pw is None or not hashpasslib.is_correct_master(pw):
            if pw == None:
                print "Bye."
                sys.exit(0)
            pw = pinentry.get_pin(description="Enter hashpass master password:",
                                  prompt="Password:",
                                  errormsg="That doesn't match the stored master.")
        hashpasslib.use_master(pw, use_bcrypt)
    except pinentry.PinEntryException:
        return get_password_cli()

def cli(arguments):
    """ Runs the app with the CLI as the user interface. """
    use_bcrypt = not arguments['--sha']

    init()
    get_password(use_bcrypt)
    if arguments['<website>']:
        w = arguments['<website>']
        result = hashpasslib.make_password(w, old=(not use_bcrypt))
        if arguments['--show']:
            print result
        else:
            hashpasslib.send_to_clipboard(result)
            print "The password is in your clipboard."
    else:
        while True:
            try:
                w = raw_input("Website name: ")
            except (KeyboardInterrupt, EOFError):
                print ""
                return
            if w == "":
                return
            result = hashpasslib.make_password(w, old=(not use_bcrypt))
            if arguments['--show']:
                print result
            else:
                hashpasslib.send_to_clipboard(result)
                print "The password is in your clipboard."

if __name__ == "__main__":
    arguments = docopt(__doc__, version='HashPass 1.0')
    if arguments["--gui"]:
        os.execl("./hashpass-gui.py", *sys.argv)
        sys.exit(-1)
    else:
        cli(arguments)
